(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'admin' AND "django_content_type"."model" = 'logentry'); args=('admin', 'logentry')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'group'); args=('auth', 'group')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'user'); args=('auth', 'user')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'permission'); args=('auth', 'permission')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'contenttypes' AND "django_content_type"."model" = 'contenttype'); args=('contenttypes', 'contenttype')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'sessions' AND "django_content_type"."model" = 'session'); args=('sessions', 'session')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'writer' AND "django_content_type"."model" = 'writer'); args=('writer', 'writer')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(7,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'writer'; args=('writer',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'article' AND "django_content_type"."model" = 'article'); args=('article', 'article')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(8,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'article'; args=('article',)
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'logentry' AND "django_content_type"."app_label" = 'admin'); args=('logentry', 'admin')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'group' AND "django_content_type"."app_label" = 'auth'); args=('group', 'auth')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auth'); args=('user', 'auth')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'permission' AND "django_content_type"."app_label" = 'auth'); args=('permission', 'auth')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'contenttype' AND "django_content_type"."app_label" = 'contenttypes'); args=('contenttype', 'contenttypes')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'session' AND "django_content_type"."app_label" = 'sessions'); args=('session', 'sessions')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'writer' AND "django_content_type"."app_label" = 'writer'); args=('writer', 'writer')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(7,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'writer'; args=('writer',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'article' AND "django_content_type"."app_label" = 'article'); args=('article', 'article')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(8,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'article'; args=('article',)
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) PRAGMA foreign_keys; args=None
(0.000) PRAGMA foreign_keys = 0; args=None
(0.000) BEGIN; args=None
CREATE TABLE "writer_writer" ("user_id" integer NOT NULL PRIMARY KEY REFERENCES "auth_user" ("id"), "pseudonym" varchar(50) NOT NULL); (params None)
(0.000) CREATE TABLE "writer_writer" ("user_id" integer NOT NULL PRIMARY KEY REFERENCES "auth_user" ("id"), "pseudonym" varchar(50) NOT NULL); args=None
(0.000) PRAGMA foreign_keys = 0; args=None
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) BEGIN; args=None
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('writer', '0001_initial', '2016-11-01 02:10:42.205711'); args=['writer', '0001_initial', '2016-11-01 02:10:42.205711']
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'admin' AND "django_content_type"."model" = 'logentry'); args=('admin', 'logentry')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'group'); args=('auth', 'group')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'permission'); args=('auth', 'permission')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'user'); args=('auth', 'user')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'contenttypes' AND "django_content_type"."model" = 'contenttype'); args=('contenttypes', 'contenttype')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'sessions' AND "django_content_type"."model" = 'session'); args=('sessions', 'session')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'writer' AND "django_content_type"."model" = 'writer'); args=('writer', 'writer')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(7,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'writer'; args=('writer',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'article' AND "django_content_type"."model" = 'article'); args=('article', 'article')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(8,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'article'; args=('article',)
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/views.py", line 28, in indexView
    request, 'index.html')
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/views.py", line 35, in indexView
    'index.html')
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 250457
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/views.py", line 28, in indexView
    request, 'index.html')
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/views.py", line 35, in indexView
    'index.html')
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 250457
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 200 121200
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 200 37045
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.0.min.js HTTP/1.1" 200 86351
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.0.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 200 121200
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 200 37045
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 121200
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 200 37045
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
"GET / HTTP/1.1" 200 4015
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/css/bootstrap.min.css'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/css/blog.css'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/js/jquery-3.1.1.min.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/js/bootstrap.min.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/css/bootstrap.min.css'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/css/blog.css'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/js/jquery-3.1.1.min.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/js/bootstrap.min.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/blog.css
Not Found: /static/js/jquery-3.1.1.min.js
Not Found: /static/js/bootstrap.min.js
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 2930
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 2927
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 2921
"GET /static/css/blog.css HTTP/1.1" 404 2900
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/js/bootstrap.min.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'static/js/bootstrap.min.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Not Found: /static/js/bootstrap.min.js
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 2921
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 121200
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 200 37045
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
"GET / HTTP/1.1" 200 4019
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) PRAGMA foreign_keys; args=None
(0.000) PRAGMA foreign_keys = 0; args=None
(0.000) BEGIN; args=None
CREATE TABLE "article_project" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "type" varchar(10) NOT NULL, "sypnosis" text NOT NULL, "creationDate" datetime NOT NULL, "writer_id" integer NOT NULL REFERENCES "writer_writer" ("user_id")); (params None)
(0.000) CREATE TABLE "article_project" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "type" varchar(10) NOT NULL, "sypnosis" text NOT NULL, "creationDate" datetime NOT NULL, "writer_id" integer NOT NULL REFERENCES "writer_writer" ("user_id")); args=None
CREATE INDEX "article_project_226b640d" ON "article_project" ("writer_id"); (params [])
(0.000) CREATE INDEX "article_project_226b640d" ON "article_project" ("writer_id"); args=[]
(0.000) PRAGMA foreign_keys = 0; args=None
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) BEGIN; args=None
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('article', '0001_initial', '2016-11-01 02:32:09.213821'); args=['article', u'0001_initial', u'2016-11-01 02:32:09.213821']
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'logentry' AND "django_content_type"."app_label" = 'admin'); args=('logentry', 'admin')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'permission' AND "django_content_type"."app_label" = 'auth'); args=('permission', 'auth')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auth'); args=('user', 'auth')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'group' AND "django_content_type"."app_label" = 'auth'); args=('group', 'auth')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'contenttype' AND "django_content_type"."app_label" = 'contenttypes'); args=('contenttype', 'contenttypes')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'session' AND "django_content_type"."app_label" = 'sessions'); args=('session', 'sessions')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'writer' AND "django_content_type"."app_label" = 'writer'); args=('writer', 'writer')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(7,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'writer'; args=('writer',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'project' AND "django_content_type"."app_label" = 'article'); args=('project', 'article')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'project' AND "django_content_type"."app_label" = 'article'); args=('project', 'article')
(0.000) BEGIN; args=None
(0.000) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('article', 'project'); args=['article', 'project']
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (9) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(9,)
(0.000) BEGIN; args=None
(0.000) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT 'Can add project', 9, 'add_project' UNION ALL SELECT 'Can change project', 9, 'change_project' UNION ALL SELECT 'Can delete project', 9, 'delete_project'; args=(u'Can add project', 9, u'add_project', u'Can change project', 9, u'change_project', u'Can delete project', 9, u'delete_project')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'article'; args=('article',)
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "django_admin_log"."content_type_id", "django_admin_log"."user_id" FROM "django_admin_log" WHERE "django_admin_log"."content_type_id" IN (8) ORDER BY "django_admin_log"."action_time" DESC; args=(8,)
(0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(8,)
(0.000) BEGIN; args=None
(0.000) DELETE FROM "auth_user_user_permissions" WHERE "auth_user_user_permissions"."permission_id" IN (24, 22, 23); args=(24, 22, 23)
(0.000) DELETE FROM "auth_group_permissions" WHERE "auth_group_permissions"."permission_id" IN (24, 22, 23); args=(24, 22, 23)
(0.000) DELETE FROM "auth_permission" WHERE "auth_permission"."id" IN (24, 22, 23); args=(24, 22, 23)
(0.000) DELETE FROM "django_content_type" WHERE "django_content_type"."id" IN (8); args=(8,)
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET / HTTP/1.1" 200 4019
"GET /static/css/bootstrap.min.css HTTP/1.1" 404 1676
"GET /static/css/blog.css HTTP/1.1" 404 1649
"GET /static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1679
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
"GET /static/js/bootstrap.min.js HTTP/1.1" 404 1670
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
"GET / HTTP/1.1" 200 4051
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4052
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 404 1695
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4052
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 404 1665
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 200 86709
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 4052
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 200 931
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 3435
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'SPE/static/images/favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'SPE/static/images/favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Not Found: /SPE/static/images/favicon.ico
"GET /SPE/static/images/favicon.ico HTTP/1.1" 404 2930
"GET / HTTP/1.1" 200 3435
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 3435
"GET / HTTP/1.1" 200 3435
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/smartif.py", line 174, in translate_token
    op = OPERATORS[token]
KeyError: 'request.user.is_authenticated:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/views.py", line 28, in indexView
    request, 'index.html')
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 944, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 876, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/template/smartif.py", line 165, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.5/dist-packages/django/template/smartif.py", line 176, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 879, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':' from 'request.user.is_authenticated:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/smartif.py", line 174, in translate_token
    op = OPERATORS[token]
KeyError: 'request.user.is_authenticated:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/views.py", line 35, in indexView
    'index.html')
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 944, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 876, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/template/smartif.py", line 165, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.5/dist-packages/django/template/smartif.py", line 176, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 879, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':' from 'request.user.is_authenticated:'
"GET / HTTP/1.1" 500 315390
"GET / HTTP/1.1" 200 3129
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 3129
"GET / HTTP/1.1" 200 3359
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css.map HTTP/1.1" 200 542194
"GET / HTTP/1.1" 200 3359
"GET /commons/static/css/bootstrap.min.css.map HTTP/1.1" 200 542194
"GET /login HTTP/1.1" 200 3221
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
"GET /login HTTP/1.1" 200 3221
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'None': None, 'False': False, 'True': True}, {'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f8ad806c0b8>>, 'DEFAULT_MESSAGE_LEVELS': {'SUCCESS': 25, 'WARNING': 30, 'DEBUG': 10, 'INFO': 20, 'ERROR': 40}, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f8ad23af8c8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f8ad239a2b0>, 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f8ad806cfd0>}, {}, {'LANGUAGE_BIDI': False, 'site_name': '127.0.0.1:8000', 'has_permission': False, 'available_apps': [], 'title': 'Log in', 'site_url': '/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7f8ad239ad68>, 'LANGUAGE_CODE': 'en-us', 'username': '', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f8ad908a160>, 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f8ad908a208>, 'next': '/admin/', 'app_path': '/admin/login/?next=/admin/'}]"
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'None': None, 'False': False, 'True': True}, {'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f8ad806c0b8>>, 'DEFAULT_MESSAGE_LEVELS': {'SUCCESS': 25, 'WARNING': 30, 'DEBUG': 10, 'INFO': 20, 'ERROR': 40}, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f8ad23af8c8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f8ad239a2b0>, 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f8ad806cfd0>}, {}, {'LANGUAGE_BIDI': False, 'site_name': '127.0.0.1:8000', 'has_permission': False, 'available_apps': [], 'title': 'Log in', 'site_url': '/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7f8ad239ad68>, 'LANGUAGE_CODE': 'en-us', 'username': '', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f8ad908a160>, 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f8ad908a208>, 'next': '/admin/', 'app_path': '/admin/login/?next=/admin/'}]"
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1669
"GET /commons/static/admin/css/login.css HTTP/1.1" 200 1203
"GET /commons/static/admin/css/base.css HTTP/1.1" 200 15937
"GET /commons/static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /commons/static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
"GET /commons/static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
"GET /login HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'registerUser'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>]], 'path': 'registerUser'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>"
Not Found: /registerUser
"GET /registerUser HTTP/1.1" 404 2879
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLPattern RegisterWriter ^RegisterWriter$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLResolver <module 'writer.article.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/article/urls.py'> (None:None) ^article/>]], 'path': 'writer/registerUser'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLPattern RegisterWriter ^RegisterWriter$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLResolver <module 'writer.article.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/article/urls.py'> (None:None) ^article/>]], 'path': 'writer/registerUser'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.article.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/article/urls.py'> (None:None) ^article/>"
Not Found: /writer/registerUser
"GET /writer/registerUser HTTP/1.1" 404 3150
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLPattern RegisterWriter ^RegisterWriter$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLResolver <module 'writer.article.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/article/urls.py'> (None:None) ^article/>]], 'path': 'writer/registerWriter'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^index>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Index ^$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Login ^login$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Logout ^logout$>], [<RegexURLResolver <module 'commons.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/commons/urls.py'> (None:None) ^>, <RegexURLPattern Home ^home$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLPattern RegisterWriter ^RegisterWriter$>], [<RegexURLResolver <module 'writer.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/urls.py'> (None:None) ^writer/>, <RegexURLResolver <module 'writer.article.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/article/urls.py'> (None:None) ^article/>]], 'path': 'writer/registerWriter'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'writer.article.urls' from '/home/francisco/Repositories/Turpial/tutorial_blog_turpial/blog/writer/article/urls.py'> (None:None) ^article/>"
Not Found: /writer/registerWriter
"GET /writer/registerWriter HTTP/1.1" 404 3156
"GET /writer/RegisterWriter HTTP/1.1" 200 3221
"GET /writer/RegisterWriter HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /writer/RegisterWriter HTTP/1.1" 200 3221
"GET /commons/static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /commons/static/css/blog.css HTTP/1.1" 304 0
"GET /commons/static/js/jquery-3.1.1.min.js HTTP/1.1" 304 0
"GET /commons/static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /login HTTP/1.1" 200 3221
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) PRAGMA foreign_keys; args=None
(0.000) PRAGMA foreign_keys = 0; args=None
(0.000) BEGIN; args=None
CREATE TABLE "article_article" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "content" text NOT NULL, "creationDate" datetime NOT NULL, "writer_id" integer NOT NULL REFERENCES "writer_writer" ("user_id")); (params None)
(0.000) CREATE TABLE "article_article" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "content" text NOT NULL, "creationDate" datetime NOT NULL, "writer_id" integer NOT NULL REFERENCES "writer_writer" ("user_id")); args=None
ALTER TABLE "article_project" RENAME TO "article_project__old"; (params [])
(0.000) ALTER TABLE "article_project" RENAME TO "article_project__old"; args=[]
CREATE TABLE "article_project" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "type" varchar(10) NOT NULL, "sypnosis" text NOT NULL, "creationDate" datetime NOT NULL); (params None)
(0.000) CREATE TABLE "article_project" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "type" varchar(10) NOT NULL, "sypnosis" text NOT NULL, "creationDate" datetime NOT NULL); args=None
INSERT INTO "article_project" ("name", "creationDate", "type", "id", "sypnosis") SELECT "name", "creationDate", "type", "id", "sypnosis" FROM "article_project__old"; (params [])
(0.000) INSERT INTO "article_project" ("name", "creationDate", "type", "id", "sypnosis") SELECT "name", "creationDate", "type", "id", "sypnosis" FROM "article_project__old"; args=[]
DROP TABLE "article_project__old"; (params [])
(0.000) DROP TABLE "article_project__old"; args=[]
CREATE INDEX "article_article_226b640d" ON "article_article" ("writer_id"); (params [])
(0.000) CREATE INDEX "article_article_226b640d" ON "article_article" ("writer_id"); args=[]
DROP TABLE "article_project"; (params [])
(0.000) DROP TABLE "article_project"; args=[]
(0.000) PRAGMA foreign_keys = 0; args=None
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) BEGIN; args=None
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('article', '0002_auto_20161101_0406', '2016-11-01 04:06:10.266309'); args=['article', '0002_auto_20161101_0406', '2016-11-01 04:06:10.266309']
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'admin' AND "django_content_type"."model" = 'logentry'); args=('admin', 'logentry')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'user'); args=('auth', 'user')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'permission'); args=('auth', 'permission')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'group'); args=('auth', 'group')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'contenttypes' AND "django_content_type"."model" = 'contenttype'); args=('contenttypes', 'contenttype')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'sessions' AND "django_content_type"."model" = 'session'); args=('sessions', 'session')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'writer' AND "django_content_type"."model" = 'writer'); args=('writer', 'writer')
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(7,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'writer'; args=('writer',)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'article' AND "django_content_type"."model" = 'article'); args=('article', 'article')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'article' AND "django_content_type"."model" = 'article'); args=('article', 'article')
(0.000) BEGIN; args=None
(0.000) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('article', 'article'); args=['article', 'article']
(0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (10) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(10,)
(0.000) BEGIN; args=None
(0.000) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT 'Can add article', 10, 'add_article' UNION ALL SELECT 'Can change article', 10, 'change_article' UNION ALL SELECT 'Can delete article', 10, 'delete_article'; args=('Can add article', 10, 'add_article', 'Can change article', 10, 'change_article', 'Can delete article', 10, 'delete_article')
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'article'; args=('article',)
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "django_admin_log"."content_type_id", "django_admin_log"."user_id" FROM "django_admin_log" WHERE "django_admin_log"."content_type_id" IN (9) ORDER BY "django_admin_log"."action_time" DESC; args=(9,)
(0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (9) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(9,)
(0.000) BEGIN; args=None
(0.000) DELETE FROM "auth_user_user_permissions" WHERE "auth_user_user_permissions"."permission_id" IN (25, 26, 27); args=(25, 26, 27)
(0.000) DELETE FROM "auth_group_permissions" WHERE "auth_group_permissions"."permission_id" IN (25, 26, 27); args=(25, 26, 27)
(0.000) DELETE FROM "auth_permission" WHERE "auth_permission"."id" IN (25, 26, 27); args=(25, 26, 27)
(0.000) DELETE FROM "django_content_type" WHERE "django_content_type"."id" IN (9); args=(9,)
